stages:
  - init
  - test
  - build
  - deploy

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

variables:
  TF_VAR_env_prefix: "dev"
  TF_VAR_runner_registration_token: $RUNNER_TOKEN

init:
  stage: init
  script:
    - terraform init
  artifacts:
    paths:
      - .terraform/
      - .terraform.lock.hcl

validate:
  stage: test
  script:
    - terraform validate
  allow_failure: true

trivy:
  stage: test
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy config --format json . > trivy.json
    - trivy config --exit-code 1 --severity HIGH,CRITICAL .
  allow_failure: true
  artifacts:
    when: always
    paths:
      - trivy.json

build:
  stage: build
  script:
    - terraform plan -out="terraform.tfplan"
  artifacts:
    paths:
      - terraform.tfplan

deploy:
  stage: deploy
  script:
    - terraform apply "terraform.tfplan"
  when: manual